<?php

define("E_2ND", "2nd");
define("E_SUP", "sup");

$__JSON_DEPT = <<<JSON
{
   "01":{
      "nom":"Ain",
      "ind":"04"
   },
   "02":{
      "nom":"Aisne",
      "ind":"03"
   },
   "03":{
      "nom":"Allier",
      "ind":"04"
   },
   "04":{
      "nom":"Alpes de Haute-Provence",
      "ind":"04"
   },
   "05":{
      "nom":"Hautes-Alpes",
      "ind":"04"
   },
   "06":{
      "nom":"Alpes-Maritimes",
      "ind":"04"
   },
   "07":{
      "nom":"Ardèche",
      "ind":"04"
   },
   "08":{
      "nom":"Ardennes",
      "ind":"03"
   },
   "09":{
      "nom":"Ariège",
      "ind":"05"
   },
   "10":{
      "nom":"Aube",
      "ind":"03"
   },
   "11":{
      "nom":"Aude",
      "ind":"05"
   },
   "12":{
      "nom":"Aveyron",
      "ind":"05"
   },
   "13":{
      "nom":"Bouches-du-Rhône",
      "ind":"04"
   },
   "14":{
      "nom":"Calvados",
      "ind":"02"
   },
   "15":{
      "nom":"Cantal",
      "ind":"04"
   },
   "16":{
      "nom":"Charente",
      "ind":"04"
   },
   "17":{
      "nom":"Charente-Maritime",
      "ind":"05"
   },
   "18":{
      "nom":"Cher",
      "ind":"02"
   },
   "19":{
      "nom":"Corrèze",
      "ind":"05"
   },
   "20":{
      "nom":"Corse",
      "ind":"04"
   },
   "21":{
      "nom":"Côte d'Or",
      "ind":"03"
   },
   "22":{
      "nom":"Côtes d'Armor",
      "ind":"02"
   },
   "23":{
      "nom":"Creuse",
      "ind":"05"
   },
   "24":{
      "nom":"Dordogne",
      "ind":"05"
   },
   "25":{
      "nom":"Doubs",
      "ind":"03"
   },
   "26":{
      "nom":"Drôme",
      "ind":"04"
   },
   "27":{
      "nom":"Eure",
      "ind":"02"
   },
   "28":{
      "nom":"Eure-et-Loir",
      "ind":"02"
   },
   "29":{
      "nom":"Finistère",
      "ind":"02"
   },
   "30":{
      "nom":"Gard",
      "ind":"04"
   },
   "31":{
      "nom":"Haute-Garonne",
      "ind":"05"
   },
   "32":{
      "nom":"Gers",
      "ind":"05"
   },
   "33":{
      "nom":"Gironde",
      "ind":"05"
   },
   "34":{
      "nom":"Hérault",
      "ind":"04"
   },
   "35":{
      "nom":"Ille-et-Vilaine",
      "ind":"02"
   },
   "36":{
      "nom":"Indre",
      "ind":"02"
   },
   "37":{
      "nom":"Indre-et-Loire",
      "ind":"02"
   },
   "38":{
      "nom":"Isère",
      "ind":"04"
   },
   "39":{
      "nom":"Jura",
      "ind":"03"
   },
   "40":{
      "nom":"Landes",
      "ind":"05"
   },
   "41":{
      "nom":"Loir-et-Cher",
      "ind":"02"
   },
   "42":{
      "nom":"Loire",
      "ind":"04"
   },
   "43":{
      "nom":"Haute-Loire",
      "ind":"04"
   },
   "44":{
      "nom":"Loire-Atlantique",
      "ind":"02"
   },
   "45":{
      "nom":"Loiret",
      "ind":"02"
   },
   "46":{
      "nom":"Lot",
      "ind":"05"
   },
   "47":{
      "nom":"Lot-et-Garonne",
      "ind":"05"
   },
   "48":{
      "nom":"Lozère",
      "ind":"04"
   },
   "49":{
      "nom":"Maine-et-Loire",
      "ind":"02"
   },
   "50":{
      "nom":"Manche",
      "ind":"02"
   },
   "51":{
      "nom":"Marne",
      "ind":"03"
   },
   "52":{
      "nom":"Haute-Marne",
      "ind":"03"
   },
   "53":{
      "nom":"Mayenne",
      "ind":"02"
   },
   "54":{
      "nom":"Meurthe-et-Moselle",
      "ind":"03"
   },
   "55":{
      "nom":"Meuse",
      "ind":"03"
   },
   "56":{
      "nom":"Morbihan",
      "ind":"02"
   },
   "57":{
      "nom":"Moselle",
      "ind":"03"
   },
   "58":{
      "nom":"Nièvre",
      "ind":"03"
   },
   "59":{
      "nom":"Nord",
      "ind":"03"
   },
   "60":{
      "nom":"Oise",
      "ind":"03"
   },
   "61":{
      "nom":"Orne",
      "ind":"02"
   },
   "62":{
      "nom":"Pas-de-Calais",
      "ind":"03"
   },
   "63":{
      "nom":"Puy-de-Dôme",
      "ind":"04"
   },
   "64":{
      "nom":"Pyrénées-Atlantiques",
      "ind":"05"
   },
   "65":{
      "nom":"Hautes-Pyrénées",
      "ind":"05"
   },
   "66":{
      "nom":"Pyrénées Orientales",
      "ind":"04"
   },
   "67":{
      "nom":"Bas-Rhin",
      "ind":"03"
   },
   "68":{
      "nom":"Haut-Rhin",
      "ind":"03"
   },
   "69":{
      "nom":"Rhône",
      "ind":"04"
   },
   "70":{
      "nom":"Haute-Saône",
      "ind":"03"
   },
   "71":{
      "nom":"Saône-et-Loire",
      "ind":"03"
   },
   "72":{
      "nom":"Sarthe",
      "ind":"05"
   },
   "73":{
      "nom":"Savoie",
      "ind":"04"
   },
   "74":{
      "nom":"Haute-Savoie",
      "ind":"04"
   },
   "75":{
      "nom":"Paris",
      "ind":"01"
   },
   "76":{
      "nom":"Seine-Maritime",
      "ind":"02"
   },
   "77":{
      "nom":"Seine-et-Marne",
      "ind":"01"
   },
   "78":{
      "nom":"Yvelines",
      "ind":"01"
   },
   "79":{
      "nom":"Deux-Sèvres",
      "ind":"05"
   },
   "80":{
      "nom":"Somme",
      "ind":"03"
   },
   "81":{
      "nom":"Tarn",
      "ind":"05"
   },
   "82":{
      "nom":"Tarn-et-Garonne",
      "ind":"05"
   },
   "83":{
      "nom":"Var",
      "ind":"04"
   },
   "84":{
      "nom":"Vaucluse",
      "ind":"04"
   },
   "85":{
      "nom":"Vendée",
      "ind":"05"
   },
   "86":{
      "nom":"Vienne",
      "ind":"05"
   },
   "87":{
      "nom":"Haute-Vienne",
      "ind":"05"
   },
   "88":{
      "nom":"Vosges",
      "ind":"03"
   },
   "89":{
      "nom":"Yonne",
      "ind":"03"
   },
   "90":{
      "nom":"Territoire de Belfort",
      "ind":"03"
   },
   "91":{
      "nom":"Essonne",
      "ind":"01"
   },
   "92":{
      "nom":"Hauts-de-Seine",
      "ind":"01"
   },
   "93":{
      "nom":"Seine-St-Denis",
      "ind":"01"
   },
   "94":{
      "nom":"Val de Marne",
      "ind":"01"
   },
   "95":{
      "nom":"Val d'Oise",
      "ind":"01"
   },
   "971":{
      "nom":"Guadeloupe",
      "ind":"05"
   },
   "972":{
      "nom":"Martinique",
      "ind":"05"
   },
   "973":{
      "nom":"Guyane",
      "ind":"05"
   },
   "974":{
      "nom":"Réunion",
      "ind":"02"
   }
}
JSON;

class Geo
{
	static $IND = array(
			"01" => "Île de France",
			"02" => "Centre, Pays de la Loire, Bretagne, Basse-Normandie, Haute-Normandie, Réunion",
			"03" => "Nord-Pas de Calais, Picardie, Bourgogne, Franche-Comté, Alsace, Lorraine, Champagne-Ardenne",
			"04" => "Languedoc-Roussillon, Auvergne, Rhône-Alpes, Provence-Alpes-Côte d'Azur, Corse",
			"05" => "Midi-Pyrénées, Aquitaine, Poitou-Charentes, Limousin, Guadeloupe, Martinique, Guyane"
		);
		
	static $DEPT;
	
	static $COURSE = array(
			E_2ND => "Secondaire",
			E_SUP => "Supérieur"
		);
	
	static $SECONDARY = array(
		"college" => "Collège",
		"lycee" => "Lycée"
	);

	
	static function _static_init()
	{
		global $__JSON_DEPT;
	
		self::$DEPT = json_decode($__JSON_DEPT, true);
	}
}
Geo::_static_init();
